### PR TITLE
Feature/jdb-attach 

### PR DESCRIPTION
**Pull request by kevinbrandon**
Added functionality to allow someone to attach to an existing instance.

### CODE REVIEW

**Comment by kevinbrandon** [comment]
Darn it... this is my first pull request in git hub.... I branched from master (which I believe was appropriate). However, I think I should have asked this to merge into develop?

**Comment by idanarye** [comment]
I usually try to follow [git-flow](http://nvie.com/posts/a-successful-git-branching-model/), which means that features should fork from `develop` and be pull-requested back to `develop`, but in this case things are a bit more tricky, since `develop` already has some breaking changes that justify a major release, but I don't want to do a major release before I add some more big features, and I can't add this big features yet because I'm too lazy(and because I have more important things to add to my other projects, which I'm also too lazy to do...).

However, there is no reason this feature should wait for a major release - it can easily go with a minor release. So, let's just merge it into `master` and do a minor release.

**Comment by idanarye** [comment]
Now, about the code itself:
1. I actually prefer a single point of entry for starting each debugger, with the `a:args` dict determining how to initialize it. Since the order of operations is important here, I'd rather have the initialization decided inside the body of the function based on `a:args` so we won't have to compromise order just because some things are called inside the wrapper initialization functions and some inside the core initialization function. There is also the matter being able to compose multiple options in different axis, as I describe in [this comment](https://github.com/idanarye/vim-vebugger/pull/7#issuecomment-74381049).
2. I intentionally didn't create a `:VBGstartJDB` command like I did with the other debuggers, and that's because Java doesn't seem to care that your .class files were once source files, and is doing you a favor that it gives you line numbers. It doesn't know about the absolute paths of the source files - it doesn't even give you relative paths to the directory they were compiled from, just the class names they came from and you should hope that they weren't package classes placed in the same file as another class... same thing with breakpoints, only this time you have to compose the breakpoint from the file path, and if it's inside an inner class you need to read the source code to determine that class name, and if it's inside an anonymous class it's so messed up that even Eclipse can't do it!
   
   But enough ranting about Java&JDB - my point is that unless you put your .java files in the project's root directory, you need to tell Vebugger what's the package root so it'll know how to translate class names to file paths and visa-versa. And you can put your source files in `./src` or in `./source` or in `./java` or in `./dudu-zar` or pretty much anywhere - Vebugger won't guess that path for you and you always have to pass it. And since passing that path in `:VBGstartJDB` will break the convention of `:VBGstart*` getting for it's first argument the executable and the rest are arguments to pass to the debugged program, I'd rather simply not add it and force users to call `vebugger#jdb#start`.
   
   Now `:VBGattachJDB` doesn't need to pass args to a debugged program there shouldn't be much of a problem to pass the source path as a second argument - it still looks weird. At any rate, if we go down this road, the command line arguments should be passed properly. Something like(not tested):

``` vim
command! -nargs=+ -complete=file VBGattachJDB call vebugger#jdb#start('',{'port': [<f-args>][0], 'srcpath':[<f-args>][1]})
```
1. I don't think `port` is the right name for the `a:args` field that determine what to attach to... In `vebugger#gdb#start` it's called `con` - but there it can be a full URL. Can `jdb --attach` get a full URL and connect to a running VM in another computer? If so, you should probably rename it to `con` for consistency.
2. Issue #11 was opened two days ago requesting that feature you are PRing. Would you mind adding a [close-commit that'll refer to it](https://help.github.com/articles/closing-issues-via-commit-messages/)?

**Comment by kevinbrandon** [comment]
Awesome great feedback. I wrote most of that in the middle of the night and I've never did a lick of vimscript before. I agree it should be "con" instead of "port" because you can attach with the string localhost:8000 as well. Easy peasy change. I was thinking of looking into seeing if the stdout of the process could be redirected at all... for now I turned off the buffer when attaching since that output should be to another terminal or a file on the system. I'll make a close commit for sure!  Additionally, I'm updating the doc for its use case... I'll do those and re-request the pull request. Do you want me to set the version 1.3.0 and merge to master and  make a pull request? Sorry noob to github opensource development (not to git).

**Comment by idanarye** [comment]
Yes, set the version to `1.3.0` please. I usually think that the only the maintainer should bump a version, but this is a special case because we are merging directly to `master`.

You might want to take GDB as an example, since it also has an attach-to-running-instance feature(both by PID and by URL - you should look at the by-URL version since it's closer to `jdb -attach`).

Also, do you mind updating the docs? Just add a line to [the optional arguments list in `doc/vebugger.txt`](https://github.com/idanarye/vim-vebugger/blob/develop/doc/vebugger.txt#L159-L162) describing what the new argument does.

**Comment by kevinbrandon** [comment]
Yup. All good with whatever direction you'd like to go amigo. I agree with the maintainer should bump a version bit. What gave me pause was "So, let's just merge it into master and do a minor release." Wasn't sure if you were wanting me to do as described or resubmit.  Hows about I'll update the docs, and try to take GDB's model for attach and see how well I can sync JDB's implementation to it. I can leave the rev of the version, tagging the version, and merging to master to you? I'd rather do this by the numbers and stick to whatever protocol / etiquette as possible (learning experience for me, since this is my first submission to opensource).  If you're good with that... should I just make all the changes as described in the feature/jdb-attach  and re-submit a pull request, or do you want me do that with a merge to master?

Following your lead!

**Comment by kevinbrandon** [comment]
You cool with assigning issue #10  to me?

**Comment by idanarye** [comment]
The thing is, I don't want a PR to `develop` because `develop` already has breaking changes that should only be at `2.0.0`, and we want to release this feature as `1.3.0`. So we need to merge it directly to `master` - but doing so with a PR will mean that `master` gets updated immediately, and I don't want that...

You know what? Let's do a release branch - I've just opened a new branch - `release-1.3`. Create a PR to there, and I'll bump the version before merging it to `master`.

As for issue #10 - it's yours. When I said to add a close-commit to #11 that was a mistake - I meant to add a close commit to #10(#11 is already linked to this PR...)

**Comment by idanarye** [comment]
I've added you as a collaborator so I can assign #10 to you.

**Comment by kevinbrandon** [comment]
Awesome. I'll get this going tonight! Thanks for the feedback and advice!

**Pull request closed without merging**
