### PR TITLE
do you have such functions of printing the stack and variable values as gdb

### PR DESCRIPTION
**Pull request by CoinCheung**
Since vim-vebugger uses gdb as the backend, can it show the value of the variables or their addresses or the stack informations as gdb does?

### CODE REVIEW

**Comment by idanarye** [comment]
First - is this _intended_ to be a pull request? Because it looks like you meant it to be an issue...

**Comment by idanarye** [comment]
* `:VBGeval` - make the debugger evaluate an expression, and print it's output. You can use it to show the value of a variable - `:VBGeval foo`.
* `:VBGevalWordUnderCursor` - same, but picks the word under the cursor - so you can put the cursor on the variable and run it to print it's value.
* `:VBGevalSelectedText` - same, but evaluates the selected text.

**Comment by CoinCheung** [comment]
Ah, I see. 
Another problem I met is how I could start debugging. In gdb or pdb, I could type in 'r' and the debugging program starts to run, while with vebugger after launching the gdb, I did not find a way to start debugging. Though I could toggle breakpoints, I could not start the first step.

**Comment by idanarye** [comment]
Vebugger automatically creates a breakpoint on `main()`(this will probably change in Vebugger 2.0 if I ever find the time(&motivation) to work on it...), so you have to run `:VBGcontinue`/`:VBGstepIn`/`:VBGstepOver` to proceed with the execution.

**Comment by CoinCheung** [comment]
OK, I thank you.

Then would you settle the output window in the bottom rather than the top of the window? Also I felt sort of weird when I find the variable values obtained via :VBGeval are not printed in the output window but in the vim default command line under the airline(hope I explain clear), would you make it print variable values to the same output window at the top?

**Comment by TamaMcGlinn** [comment]
This should be closed as it does not add any commits; it just suggests to merge your develop into your master. This is confusing because this appears to be an unmerged pullrequest that adds the feature requested.

**Pull request closed without merging**
