### PR TITLE
Added LLDB debugger support

### PR DESCRIPTION
**Pull request by IngoMeyer441**
Added LLDB debugger support by using the lldb python API

### CODE REVIEW

**Comment by IngoMeyer441** [comment]
I have written a small python script that uses the LLDB python API since the LLDB executable has no machine interface option like GDB. Vebugger in turn calls that python script.
I've tested it on Linux and macOS. Unfortunately, `VBGattachLLDB` did not work for me (tested on Linux), but VBGattachGDB did not work either (and I don't know why).

**Comment by idanarye** [comment]
It looks fine, but I see you keep adding things. Tell me when it's ready for merge.

**Comment by IngoMeyer441** [comment]
I have tested the lldb extension for the last two months and it works well so far. However, there are still two issues:
- I did not test remote debugging with lldb so I don't know if it works at all (but it is implemented).
- It is not possible (yet) to set another entry point than `main`. LLDB doesn't know GDB's `tbreak` command.

Since remote debugging is not tested yet, it is not mentioned in the updated documentation.

**Comment by idanarye** [comment]
Very well. I was thinking of removing the automatic break on main for V2 anyways...

**Pull request merged**
